### ISSUE TITLE
.swift files depend on unknown ColoredView

### ISSUE THREAD

**Issue by DivineDominion** [phranck/CCNPreferencesWindowController#11]
I found the .swift files don't work at the moment because the `headerView` outles is of unknown type `ColoredView`.

/cc @BrunoVandekerkhove

**Comment by BrunoVandekerkhove** [comment]
Yes, my computer broke and I have exams so it'll take a few weeks to properly fix this (+ add an example and update the podspec). 

Attached is the code for ColoredView, probably best to rename the class as to be prefixed properly, and add the code under the definition of CCNPreferencesWindow.

[ColoredView.txt](https://github.com/phranck/CCNPreferencesWindowController/files/93360/ColoredView.txt)
